image: node:lts

cache:
  paths:
    - node_modules
    - .yarn

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Installing dependencies"
    - yarn install
    - echo "Building application"
    - yarn build

test:
  # cypress images may not be up to date.
  # refer to: https://hub.docker.com/r/cypress/base/tags
  image: cypress/base:16
  stage: test
  script:
    - yarn install
    - yarn cypress install
    - echo "Checking format code eslint"
    - yarn eslint .
    - echo "Checking types"
    - yarn tsc --noEmit
    - echo "Running tests"
    - yarn test:ci
